language: go
dist: bionic
services:
  - docker
# Whenever the Go version is updated here, .circleci/config.yml and .promu.yml
# should also be updated.
go:
- 1.12.x

go_import_path: github.com/prometheus/prometheus

# This ensures that the local cache is filled before running the CI.
# travis_retry retries the command 3 times if it fails as we've experienced
# random issues on Travis.
before_install:
- travis_retry make deps
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make; fi

script:
- make check_license style unused test lint check_assets
- git diff --exit-code
- ./fuzzit.sh

env:
  global:
    # This is FUZZIT_API_KEY environment variable
    secure: DhQmBKuIbrkwoTDSCW5zVDrtq5YBWdJooyfPxJB5Ms1hYoiiJg+8d9BMcdEtT+n+KxXGd1vAjSwIdPILqIUBM1aw3f8W9926kSuuK2N+ObcuvtDYYgx76VdVqRoEbgE8chrbVV3QxH8YfdzcUwGSZmzpHUdL/7JZbSugKr6oZN8=
